version: '3.8'

services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - NODE_ENV=production
    depends_on:
      - python-app

  python-app:
    build:
      context: ./bots
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./bots:/usr/src/app
